### Continuation of example use case script: Modeling RMP with respect to solution components.
### Take output of modelUseCase.R and estimate average within-cell type effects per solution component
### using Mixed-effects models
### 
# Author: Shreejoy Tripathy
# Contact: stripat3@gmail.com

libs <- c('broom', 'lme4')

library(broom)
library(lme4)

for (L in libs){
  if(!require(L, character.only = T)) {
    install.packages(L, dep = T, quiet = T)
    
    if (!require(L, character.only = T)) {
      suppressWarnings(biocLite(L))
    }
  }
}

plot_data_list_out <- readRDS('Data/rmp_adjusted_data_frames.RDS')

# lapply loop that goes through output of plot_data_list_out (generated by modelUseCase.R)
# and fits a mixed effects model to estimate beta coeffs between rmp and each solution component
# after controlling for neuron names and pmids
regress_df = lapply(names(plot_data_list_out), function(curr_feature){
  
  dataset = plot_data_list_out[[curr_feature]]
  
  # estimate models using 95% of data - to exclude text-mining outliers
  use_range = quantile(dataset  %>% pull(curr_feature), probs = c(.05, .95))
  
  names(use_range) = c('lower_bound', 'upper_bound')

  filt_dataset = dataset[dataset[curr_feature] >= use_range[1] & dataset[curr_feature] <= use_range[2], ]
  
  # ep_shifted is the adjusted rmp value
  frml_2 = paste('ep_shifted ~ ', curr_feature, '+ (1|NeuronName) + (1|Pmid)')
  frml_1 = paste('ep_shifted ~ (1|NeuronName) + (1|Pmid)')
  
  
  model_2 = lmer(formula = frml_2, 
                 data = filt_dataset)
  model_1 = lmer(formula = frml_1, 
                 data = filt_dataset)
  
  anova_out = anova(model_1, model_2) %>% tidy()
  
  return(c(tidy(model_2)[2, ], anova_out[2, 'p.value'], use_range))
  
  
}) %>% bind_rows()
regress_df$term = gsub("_0_", "_", regress_df$term)


# plot scatter plots for specific cell types 
show_cell_types = c("Hippocampus CA1 pyramidal cell", "Neocortex basket cell", 
                    "Neocortex pyramidal cell layer 5-6", "Neocortex pyramidal cell layer 2-3", "Other", "Neocortex Martinotti cell")

plot_feature = 'internal_0_Na'

low_limit = regress_df[regress_df$term == 'internal_Na', 'lower_bound'] %>% as.numeric()
upper_limit = regress_df[regress_df$term == 'internal_Na', 'upper_bound'] %>% as.numeric()


int_na_scatter = plot_data_list_out[[plot_feature]] %>% 
  filter(internal_0_Na >= low_limit, internal_0_Na <= upper_limit, NeuronName %in% show_cell_types) %>% 
  distinct(Pmid, .keep_all = T) %>% 
  ggplot(aes(x = internal_0_Na, y = ep_shifted)) + 
  geom_point() + geom_smooth(method = "lm") + facet_wrap(~NeuronName, scales = "free_y") +
  xlab('internal Na (mM)') + ylab('Vrest (mV)')

plot_feature = 'internal_0_GTP'

low_limit = regress_df[regress_df$term == 'internal_GTP', 'lower_bound'] %>% as.numeric()
upper_limit = regress_df[regress_df$term == 'internal_GTP', 'upper_bound'] %>% as.numeric()

int_gtp_scatter = plot_data_list_out[[plot_feature]] %>% 
  filter(internal_0_GTP >= low_limit, internal_0_GTP <= upper_limit, NeuronName %in% show_cell_types) %>% 
  distinct(Pmid, .keep_all = T) %>% 
  ggplot(aes(x = internal_0_GTP, y = ep_shifted)) + 
  geom_point() + geom_smooth(method = "lm") + facet_wrap(~NeuronName, scales = "free_y") +
  xlab('internal GTP (mM)') + ylab('Vrest (mV)')


# plot bar graphs for beta-coeffs
plot_1_all_data = regress_df %>% ggplot(aes(x = term, y = estimate)) + geom_hline(yintercept = 0, linetype = 2) + 
  geom_bar(stat = "identity", fill = "turquoise") + 
  geom_linerange(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + 
  theme(axis.text.x = element_text(angle=90, hjust=1)) + #ylim(-1, 1) + 
  ylab('Beta coeff slope (mV/mM)') + xlab('')

plot_1_ylim = regress_df %>% ggplot(aes(x = term, y = estimate)) + geom_hline(yintercept = 0, linetype = 2) + 
  geom_bar(stat = "identity", fill = "turquoise") + 
  geom_linerange(aes(ymin = estimate - std.error, ymax = estimate + std.error)) + 
  theme(axis.text.x = element_text(angle=90, hjust=1)) + ylim(-1, 1) + ylab('Beta coeff slope (mV/mM)') + 
  ggtitle('')

rmp_beta_bar_graphs = plot_grid(plot_1_all_data, plot_1_ylim, nrow = 2)

ggsave(plot=rmp_beta_bar_graphs,height=10, width=8,dpi=200, filename = paste0(getwd(), "/Plots/univariatePlots/rmp_beta_bar_graphs", ".pdf"), useDingbats=FALSE)


scatter_plots = plot_grid(int_gtp_scatter, int_na_scatter, nrow = 2)
ggsave(plot=scatter_plots,height=10, width=10,dpi=200, filename = paste0(getwd(), "/Plots/univariatePlots/scatter_plots", ".pdf"), useDingbats=FALSE)

# save csv with results of beta coeffs and pvalues
write.csv(regress_df %>% select(term, estimate, std.error, p.value) %>% rename(beta = estimate) %>% as_tibble(), file = '~/InterLabEphysVar/Plots/univariatePlots/beta_table.csv')



